const datas = [
  {
    data: {
      site_name: "Stream LLapi TV",
      site_logo:
        "https://adminview.streamhash.com/storage/uploads/settings/SV-2021-09-21-23-33-49-1d56ae5cd94528435e5bc8e83bdcd1bf5edc813f.png",
      site_icon:
        "https://adminview.streamhash.com/storage/uploads/settings/SV-2021-09-21-23-33-49-8cbdf4735f2fcac1d9841344e05bedc4ed8fadca.png",
      tag_name: "Stream LLapi TV",
      browser_key: "",
      default_lang: "en",
      currency: "$",
      admin_delete_control: "0",
      installation_process: "1",
      amount: "10",
      expiry_days: "28",
      admin_take_count: "12",
      google_analytics: "",
      streaming_url: "https://adminview.streamhash.com:8081/",
      video_compress_size: "50",
      image_compress_size: "8",
      s3_bucket: "",
      track_user_mail: "",
      REPORT_VIDEO: "Captions issue.",
      VIDEO_RESOLUTIONS: "1920x1080",
      redeem_paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr",
      custom_users_count: "50",
      admin_language_control: "1",
      post_max_size: "2000M",
      upload_max_size: "2000M",
      minimum_redeem: "1",
      redeem_control: "1",
      admin_commission: "10",
      user_commission: "90",
      home_page_bg_image:
        "https://adminview.streamhash.com//images/home_page_bg_image.jpg",
      common_bg_image:
        "https://adminview.streamhash.com/storage/uploads/settings/SV-2021-09-21-23-36-27-4e21d072ec07c69d3c0c80b78163f657ecba0419.png",
      stripe_publishable_key: "pk_test_uDYrTXzzAuGRwDYtu7dkhaF3",
      stripe_secret_key: "sk_test_lRUbYflDyRP3L2UbnsehTUHW",
      video_viewer_count: "1",
      amount_per_video: "100",
      facebook_link: "",
      linkedin_link: "",
      twitter_link: "",
      google_plus_link: "",
      pinterest_link: "",
      instagram_link: "",
      appstore: "",
      playstore: "",
      copyright_content: "Copyrights 2018 . All rights reserved.",
      contact_email: "",
      contact_address: "",
      contact_mobile: "",
      watermark_logo:
        "https://adminview.streamhash.com/storage/uploads/settings/SV-2021-09-01-08-49-22-e951b386e70cf31ce451d3a1bca93be1f9967022.png",
      referral_earnings: "15",
      referrer_earnings: "20",
      download_video_expiry_days: "3",
      is_jwplayer_configured_mobile: "0",
      jwplayer_key_mobile:
        "3FqL/SpvVBWLTmzbGsWMN5QGtFxz/V+KTAH2uZpHiNZTK7G2g91lMuiGeuwcZ+fR",
      currency_code: "USD",
      max_banner_count: "6",
      max_home_count: "6",
      max_original_count: "20",
      is_home_category_feature: "0",
      token_expiry_hour: "1000000",
      is_subscription: "1",
      is_spam: "1",
      is_payper_view: "1",
      socket_url: "https://adminview.streamhash.com:3003/",
      FB_CLIENT_ID: "976184499829139",
      FB_CLIENT_SECRET: "afd54361bef2b63b1c49fca36f72cba6",
      FB_CALL_BACK: "https://demo.streamhash.com/",
      TWITTER_CLIENT_ID: "",
      TWITTER_CLIENT_SECRET: "",
      TWITTER_CALL_BACK: "",
      GOOGLE_CLIENT_ID:
        "617297315930-di00jtbgplgrmr9sd0ks291sj1lctio3.apps.googleusercontent.com",
      GOOGLE_CLIENT_SECRET: "nHbIJ3nYBWNKif24FFWrNvtq",
      GOOGLE_CALL_BACK: "https://demo.streamhash.com/",
      social_email_suffix: "@streamhash.com",
      meta_title: "StreamHash",
      meta_description: "StreamHash",
      meta_author: "StreamHash",
      meta_keywords: "StreamHash",
      header_scripts: "",
      body_scripts: "",
      ANGULAR_SITE_URL: "https://demo.streamhash.com/",
      is_push_notification: "1",
      no_of_static_pages: "8",
      MAILGUN_PUBLIC_KEY: "",
      MAILGUN_PRIVATE_KEY: "",
      is_mailgun_check_email: "0",
      ios_payment_subscription_status: "0",
      prefix_file_name: "SV",
      ffmpeg_installed: "1",
      email_verify_control: "0",
      email_notification: "1",
      demo_admin_email: "admin@streamview.com",
      is_watermark: "0",
      JWPLAYER_KEY: "M2NCefPoiiKsaVB8nTttvMBxfb1J3Xl7PDXSaw==",
      HLS_STREAMING_URL: "https://adminview.streamhash.com:8081/",
      JWPLAYER_KEY_ANDRIOD: "",
      JWPLAYER_KEY_IOS: "",
      video_player_type: "2",
      RTMP_SECURE_VIDEO_URL: "https://adminview.streamhash.com:8081/",
      HLS_SECURE_VIDEO_URL: "https://adminview.streamhash.com:8081/",
      VIDEO_SMIL_URL: "",
      demo_admin_password: "123456",
      promo_video:
        "https://adminview.streamhash.com/uploads/settings/SV-2021-09-01-08-49-22-84bf108940e505e71c323fc9f1d86397a8443849.mp4",
      is_promo_video_enabled: "0",
      home_banner_heading:
        "LLapi Stream ofron Filma Me Titra Shqip Live Kanale",
      home_banner_title: "Watch anywhere. Cancel anytime.",
      home_banner_description: "LLapi Stream",
      home_section_1_title: "Argetohu tek ne pa kufi",
      home_section_1_description: "LLapi Stream portali numer 1",
      home_section_1_video:
        "https://adminview.streamhash.com//images/enjoy_on_tv.m4v",
      home_section_2_title: "Download your shows to watch offline.",
      home_section_2_description:
        "Save your favourites easily and always have something to watch.",
      home_section_2_image:
        "https://adminview.streamhash.com//images/mobile.jpg",
      home_section_2_mob_image:
        "https://adminview.streamhash.com//images/boxshot.png",
      home_section_2_image_title: "Stranger Things",
      home_section_3_title: "Watch everywhere.",
      home_section_3_description:
        "Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV.",
      home_section_3_video:
        "https://adminview.streamhash.com//images/watch_everywhere.m4v",
      home_section_3_cover_image:
        "https://adminview.streamhash.com//images/all-device.png",
      is_watermark_logo_enabled: "1",
      watermark_position: "top-right",
      referral_earnings_amount: "30",
      web_jw_player_paid_version: "1",
      andriod_jw_player_paid_version: "1",
      ios_jw_player_paid_version: "1",
      jw_player_key_web: "X6vykLrnos0UM2n1ga4pH+8MqPQO11a5d8wBeccRsfqkd06F",
      jw_player_key_andriod: "X6vykLrnos0UM2n1ga4pH+8MqPQO11a5d8wBeccRsfqkd06F",
      jw_player_key_ios: "X6vykLrnos0UM2n1ga4pH+8MqPQO11a5d8wBeccRsfqkd06F",
      PAYPAL_ID:
        "AaXkweZD5g9s0X3BsO0Y4Q-kNzbmLZaog0mbmVGrTT5IX0O73LoLVcHp17e6pkG7Vm04JEUuG6up30LD",
      PAYPAL_SECRET:
        "EIfMWa-9AGbiGFawmFc906KPkm3Dm717pp2KW6x0PJ1_dbt4dnU0pZlp1d6RhF56UIzRAIka7dGBpeGy",
      PAYPAL_MODE: "sandbox",
      footer_pages1: [
        {
          page_id: 1,
          unique_id: "about",
          page_type: "about",
          heading: "about",
        },
        {
          page_id: 2,
          unique_id: "contact",
          page_type: "contact",
          heading: "contact",
        },
        {
          page_id: 3,
          unique_id: "privacy",
          page_type: "privacy",
          heading: "privacy",
        },
        {
          page_id: 4,
          unique_id: "terms",
          page_type: "terms",
          heading: "terms",
        },
        { page_id: 5, unique_id: "help", page_type: "help", heading: "help" },
      ],
      footer_pages2: [
        { page_id: 7, unique_id: "faq", page_type: "faq", heading: "FAQ" },
      ],
      social_logins: {
        FB_CALL_BACK: "https://demo.streamhash.com/",
        FB_CLIENT_ID: "976184499829139",
        FB_CLIENT_SECRET: "afd54361bef2b63b1c49fca36f72cba6",
        GOOGLE_CALL_BACK: "https://demo.streamhash.com/",
        GOOGLE_CLIENT_ID:
          "617297315930-di00jtbgplgrmr9sd0ks291sj1lctio3.apps.googleusercontent.com",
        GOOGLE_CLIENT_SECRET: "nHbIJ3nYBWNKif24FFWrNvtq",
        TWITTER_CALL_BACK: "",
        TWITTER_CLIENT_ID: "",
        TWITTER_CLIENT_SECRET: "",
      },
    },
  },
];
export default datas;
